name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          npm install

      # Run backend tests
      - name: Run Backend Tests
        run: |
          echo "No backend tests yet"

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      # Build frontend
      - name: Build Frontend
        run: |
          cd client
          npm run build
